# Generated by Django 5.1.5 on 2025-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.CharField(default='System', max_length=255),
        ),
    ]
