# Generated by Django 5.1.5 on 2025-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapi', '0002_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listing_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
