# Generated by Django 5.1.5 on 2025-02-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapi', '0003_item_listing_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='listing_worker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
